version: "3"
services:
  db:
    image: mysql

    environment:
      - MYSQL_ROOT_HOST=${DB_ROOT_HOST}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}

    ports:
      - "3306:3306"

    volumes:
      - ./db/conf:etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
      - ./db/logs:/var/log/mysql

    networks:
      - backend

  api:
    image: node

    environment:
      - MYSQL_SERVER=db
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - TZ=${TZ}
      - CHOKIDAR_USEPOLLING=true

    # コンテナを起動させ続けるように設定
    tty: true

    ports:
      - "3000:3000"

    # ホスト側の./apiをコンテナの/appにマウント
    volumes:
      - ./api:/app

    # 起動時のカレントフォルダ設定
    working_dir: /app

    # 起動後の自動実行コマンドの設定
    command: npm run dev

    networks:
      - backend

    # 依存関係：dbコンテナが起動した後にapiコンテナが起動するように設定
    depends_on:
      - db

  vue:
    image: node
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./client:/app
    working_dir: /app
    command: npm run serve
    networks:
      - backend
    depends_on:
      - api

networks:
  backend:

volumes:
  mysqldata:
